
version: '3.8'

services:
  vault-init:
    image: alpine:latest
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    command: |
      sh -c "
        chown -R 100:1000 /vault/data /vault/logs &&
        chmod -R 755 /vault/data /vault/logs
      "

  vault:
    image: hashicorp/vault:1.15
    container_name: vault-prod
    restart: unless-stopped
    depends_on:
      - vault-init
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      VAULT_ADDR: https://0.0.0.0:8200
      VAULT_API_ADDR: https://0.0.0.0:8200
      VAULT_DISABLE_MLOCK: "true"
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - ./vault.hcl:/vault/config/vault.hcl:ro
      - ./certs:/vault/certs:ro
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault-network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vault-backup:
    image: alpine:latest
    container_name: vault-backup
    restart: unless-stopped
    volumes:
      - vault-data:/vault/data:ro
      - ./backups:/backups
    environment:
      - VAULT_BACKUP_SCHEDULE=0 2 * * *
    command: |
      sh -c "
        apk add --no-cache dcron &&
        echo '0 2 * * * cp -r /vault/data/* /backups/' | crontab - &&
        crond -f
      "
    networks:
      - vault-network

volumes:
  vault-data:
    driver: local
  vault-logs:
    driver: local
  vault-config:
    driver: local

networks:
  vault-network:
    driver: bridge
