
version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault-prod
    restart: unless-stopped
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      VAULT_ADDR: https://0.0.0.0:8200
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {"file": {"path": "/vault/data"}},
          "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": false}},
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - vault-config:/vault/config
      - ./vault-config.hcl:/vault/config/vault.hcl:ro
      - ./certs:/vault/certs:ro
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault-network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vault-backup:
    image: alpine:latest
    container_name: vault-backup
    restart: unless-stopped
    volumes:
      - vault-data:/vault/data:ro
      - ./backups:/backups
    environment:
      - VAULT_BACKUP_SCHEDULE=0 2 * * *
    command: |
      sh -c "
        apk add --no-cache dcron &&
        echo '0 2 * * * cp -r /vault/data/* /backups/' | crontab - &&
        crond -f
      "
    networks:
      - vault-network

volumes:
  vault-data:
    driver: local
  vault-logs:
    driver: local
  vault-config:
    driver: local

networks:
  vault-network:
    driver: bridge
